### ISSUE TITLE
FetchData - Regresar solamente un usuario cuando se manda ID

### ISSUE THREAD

**Issue by Tenorio94** [aledi/focus#107]
Actualmente las acciones regresan todos los datos de la tabla respectiva de la base de datos. Para no iterar a cada rato que se hace la llamada, mejor hacer el caso de cuando se manda el id regresar solamente el usuario del id.

Los casos son:

modify-clientes
'GET_CLIENTES'

modify-administrador
'GET_ADMINS'

modify-survey
'GET_ENCUESTAS'

modify-paneles
'GET_PANELES'

**Comment by ecristerna** [comment]
@alexcris qué crees que sea mejor aquí, guardar todo cuando hacen el fetch completo para llenar la tabla de todos los usuarios, o volver a hacer un fetch y que te regrese solo el que me pides?

**Comment by acristernam** [comment]
pero en dónde se guardarían todos? según yo no los guardamos, solo los desplegamos no? si es así, entonces me parece buena idea que si quiero solamente un usuario, me regrese nada más a ese usuario y no todos.

**Comment by ecristerna** [comment]
ahorita no los están guardando; pero una opción es guardarlos para después localmente sacar el que se va a modificar, o lo de solo regresar uno

**Comment by acristernam** [comment]
si se van a guardar, entonces es mejor idea eso. sacarlo de donde lo tengamos guardado.

**Comment by acristernam** [comment]
Así no hacemos llamadas de más.
