### ISSUE TITLE
Remove "Preguntas" section

### ISSUE THREAD

**Issue by ecristerna** [aledi/focus#120]
Creo que la sección de preguntas no deberíamos mostrarla, porque no tiene sentido hacer una pregunta que no esté ligada a una encuesta, y para modificar una pregunta, puedes irte desde el tab de encuestas.

Aparte, si dejamos crear una pregunta, aún seleccionando una encuesta a la cual ligarla, habría que buscar en qué número de pregunta vamos. Mejor solo dejarlo desde `Encuestas`

**Comment by Tenorio94** [comment]
Ok, recuerdo que lo habíamos dejado para mostrarlo en el demo. Pero ahorit aquito la opción del navbar

**Comment by acristernam** [comment]
@Tenorio94 tú estás con esto?

**Comment by Tenorio94** [comment]
@alexcris  Ya lo hice, es el PR pendiente. Me dijo Eduardo que se va a esperar a ver qué le dicen antes de hacer merge
