### ISSUE TITLE
Do not delete relational records every time update is made

### ISSUE THREAD

**Issue by ecristerna** [aledi/focus#128]
Ahorita, cuando se liga un panelista a un panel, o una pregunta a una encuesta, primero se borran los records que hayan en la tabla para el panel o encuesta, para evitar duplicados; hay que ver la forma de no tener que borrarlos y que no se dupliquen.

**Comment by ecristerna** [comment]
@Tenorio94 alguna idea de cómo?

**Comment by Tenorio94** [comment]
@ecristerna Con un 'Update' en la tabla en vez de borrar, creo que filtrando por el id del panel que se está mandando se puede hacer.

**Comment by Tenorio94** [comment]
@ecristerna  UPDATE panel-panelista SET viejo=nuevoPanelista
WHERE idPanel = idSent

algo así es lo que se me ocurre
