### ISSUE TITLE
Preguntas: Do not render all 10 options

### ISSUE THREAD

**Issue by acristernam** [aledi/focus#154]
Lo que deberíamos de hacer si escoge cualquiera de estos tres casos, es mejor render dos opciones y que haya un botón para agregar otra opción.

**Comment by acristernam** [comment]
@ecristerna afecta en algo esto? Por ejemplo si solo se manda una pregunta de opción múltiple con 4 opciones? O nunca se mandan las 10 opciones si no las llenó todas?

**Comment by Tenorio94** [comment]
@alexcris de hecho esto se lo estaba comentando a Eduardo, estamos de acuerdo que sería mejor que existiera el botón de 'Add Option'. Ya me haré bolas con ese botón en el transcurso de la semana. Me asignaré el issue

**Comment by acristernam** [comment]
@Tenorio94 ayer lo intenté y sí está muy complicado jaja 😞

**Comment by acristernam** [comment]
y más si queremos que también tenga un 'Remove option'

**Comment by ecristerna** [comment]
@Tenorio94 creo que mejor hay que darle prioridad a lo otro; esto puede quedar pendiente
