### ISSUE TITLE
Reportes: Download

### ISSUE THREAD

**Issue by ecristerna** [aledi/focus#249]

**Comment by acristernam** [comment]
@ecristerna puedes poner aquí la estructura de cómo mandas la respuesta? también el endpoint al que tengo que hacer el request.

**Comment by ecristerna** [comment]
llamada

```
{
   action: 'DOWNLOAD_DATA',
   encuesta: id
}
```

respuesta

```
{
   columnas: [...],
   filas: [{
              nombre:
              genero: 
              edad:
              educacion:
              municipio:
              estado:
              respuestas: []
           }, {},...]
}
```

la llave de columnas es un arreglo de strings con los encabezados de cada columna. al principio siempre tiene los mismos `nombre, genero, edad, educacion, municipio, estado` y a partir del séptimo vienen las preguntas para esa encuesta.

la llave filas es un arreglo de objetos, cada objeto es una fila, y tiene esas llaves, donde cada llave es una celda, y la llave respuestas es un arreglo de strings con las respuestas a cada una de las preguntas.

count(columnas) == 6 + count(filas[i].respuestas)

<img width="525" alt="captura de pantalla 2016-10-02 a la s 23 16 46" src="https://cloud.githubusercontent.com/assets/3680271/19027460/56bd36a8-88f6-11e6-8fde-9f1f4599e256.png">
