### ISSUE TITLE
Cambiar estilos de aplicación web

### ISSUE THREAD

**Issue by Tenorio94** [aledi/focus#75]
- Cambiar el logo
- Mover el logo en la pantalla de sign-in para mantener consitencia
- Cambiar color de la barra principal a azul igual que el logo.

**Comment by acristernam** [comment]
@Tenorio94 los colores ya los cambié en https://github.com/ecristerna/focus/pull/85

**Comment by acristernam** [comment]
@Tenorio94 puedes actualizar el logo?
